# Built with https://github.com/squidfunk/mkdocs-material

site_name: ZoomImage
site_url: 'https://github.com/panpf/zoomimage'
site_author: '2024 panpf'
site_description: 'An gesture zoom viewing of images library specially designed for Compose Multiplatform and Android View. Supported scale, pan, locate, rotation, and super-large image subsampling.'

repo_name: 'ZoomImage'
repo_url: 'https://github.com/panpf/zoomimage'

copyright: 'Copyright &copy; 2024 panpf'

theme:
  name: 'material'
  language: 'en'
  favicon: 'images/logo.ico'
  logo: 'images/logo.png'
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: 'JetBrains'
    code: 'JetBrains Mono'
  features:
    - content.tabs
    - content.code.annotate
    - content.code.copy
    #    - navigation.tabs
    #    - navigation.top
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - search.highlight
    - search.suggest
    - search.share

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/panpf/zoomimage'

nav:
  - 'Overview': index.md
  - 'Getting Started': getting_started.md
  - 'Scale': scale.md
  - 'Offset': offset.md
  - 'Rotate': rotate.md
  - 'Locate': locate.md
  - 'Read Mode': readmode.md
  - 'Click': click.md
  - 'Subsampling': subsampling.md
  - 'Scroll Bar': scrollbar.md
  - 'Log': log.md
  - 'Modifier.zoom()': modifier_zoom.md
  - 'Change Log': CHANGELOG.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences  # 支持代码块嵌套
  - pymdownx.tabbed       # 支持选项卡
  - pymdownx.tasklist     # 支持任务列表
  - pymdownx.emoji        # 支持 Emoji
  - pymdownx.details      # 支持折叠内容
  - pymdownx.highlight    # 支持代码高亮
  - tables                # 支持表格
  - footnotes             # 支持脚注
  - attr_list             # 支持属性列表
  - md_in_html            # 支持在 HTML 中嵌入 Markdown

plugins:
  - i18n:
      docs_structure: suffix
      default_language: en
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          default: false
          name: 中文
          build: true
  - search
  - minify:
      minify_html: true

validation:
  #  links:
  #    absolute_links: ignore
  nav:
    omitted_files: ignore