name: Deploy Publish Release

on:
  push:
    tags:
      - '*'

jobs:
  #  test:
  #    name: Unit tests
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Check out the repository
  #        uses: actions/checkout@v2
  #
  #      - name: Set up JDK
  #        uses: actions/setup-java@v4
  #        with:
  #          distribution: temurin
  #          java-version: 17
  #
  #      - name: Run desktop test
  #        run: ./gradlew desktopTest

  package-android:
    name: Package android
    #    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Run package
        run: ./gradlew sample:assembleRelease

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk-files
          path: sample/build/outputs/apk/release/*.apk

  package-ios:
    name: Package ios
    #    needs: test
    runs-on: macos-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run package
        run: xcodebuild -project sample/iosApp/iosApp.xcodeproj -scheme iosApp -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO -derivedDataPath sample/build/ios/outputs/

      - name: Read version name
        id: version_name_step
        run: |
          versionName=$(grep '^versionName=' gradle.properties | awk -F'=' '{print $2}')
          echo "version_name=$versionName" >> $GITHUB_OUTPUT

      - name: File name add version
        run: mv "sample/build/ios/outputs/Build/Products/Debug-iphonesimulator/ZoomImage Sample.app" "sample/build/ios/outputs/Build/Products/Debug-iphonesimulator/ZoomImage Sample-${{ steps.version_name_step.outputs.version_name }}.app"

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-files
          path: sample/build/ios/outputs/Build/Products/Debug-iphonesimulator/*.app

  package-linux:
    name: Package linux desktop
    #    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run package
        run: ./gradlew sample:packageReleaseDeb

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deb-files
          path: sample/build/compose/binaries/main-release/deb/*.deb

  package-macos:
    name: Package macos desktop
    #    needs: test
    runs-on: macos-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run package
        run: ./gradlew sample:packageReleaseDmg

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dmg-files
          path: sample/build/compose/binaries/main-release/dmg/*.dmg

  package-windows:
    name: Package windows desktop
    #    needs: test
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run package
        run: ./gradlew sample:packageReleaseMsi

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: msi-files
          path: sample/build/compose/binaries/main-release/msi/*.msi

  package-js:
    name: Package js browser
    #    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run package
        run: ./gradlew sample:jsBrowserDistribution

      - name: Read version name
        id: version_name_step
        run: |
          versionName=$(grep '^versionName=' gradle.properties | awk -F'=' '{print $2}')
          echo "version_name=$versionName" >> $GITHUB_OUTPUT

      - name: Compress
        run: cd sample/build/dist/js/productionExecutable; zip -r "zoomimage-sample-js-${{ steps.version_name_step.outputs.version_name }}.zip" *; cd -

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: js-browser-files
          path: sample/build/dist/js/productionExecutable/*.zip

  package-wasm-js:
    name: Package wasm js browser
    #    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run package
        run: ./gradlew sample:wasmJsBrowserDistribution

      - name: Read version name
        id: version_name_step
        run: |
          versionName=$(grep '^versionName=' gradle.properties | awk -F'=' '{print $2}')
          echo "version_name=$versionName" >> $GITHUB_OUTPUT

      - name: Compress
        run: cd sample/build/dist/wasmJs/productionExecutable; zip -r "zoomimage-sample-wasmJs-${{ steps.version_name_step.outputs.version_name }}.zip" *; cd -

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-js-browser-files
          path: sample/build/dist/wasmJs/productionExecutable/*.zip

  deploy-api-docs:
    name: Deploy API docs
    needs: [ package-android, package-ios, package-linux, package-macos, package-windows, package-js, package-wasm-js ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build the api docs
        run: ./gradlew dokkaHtmlMultiModule

      - name: Check out the gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages

      - name: Remove old api directory
        run: |
          rm -rf api/*

      - name: Create api directory
        run: mkdir -p api

      - name: Move build artifacts to api directory
        run: |
          mv build/dokka/htmlMultiModule/* api/

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "Update api docs"
          branch: gh-pages
          file_pattern: api/*

  publish:
    name: Publish and release to maven central
    needs: deploy-api-docs
    runs-on: macos-latest
    steps:
      - name: Checkout
        id: check
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Run publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
  #        run: ./gradlew publishToMavenCentral --no-configuration-cache

  release:
    name: Release new version
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download APK artifacts
        uses: actions/download-artifact@v4
        with:
          name: apk-files
          path: ./downloaded

      - name: Download ios artifacts
        uses: actions/download-artifact@v4
        with:
          name: ios-files
          path: ./downloaded

      - name: Download deb artifacts
        uses: actions/download-artifact@v4
        with:
          name: deb-files
          path: ./downloaded

      - name: Download dmg artifacts
        uses: actions/download-artifact@v4
        with:
          name: dmg-files
          path: ./downloaded

      - name: Download msi artifacts
        uses: actions/download-artifact@v4
        with:
          name: msi-files
          path: ./downloaded

      - name: Download js-browser artifacts
        uses: actions/download-artifact@v4
        with:
          name: js-browser-files
          path: ./downloaded

      - name: Download wasm-js-browser artifacts
        uses: actions/download-artifact@v4
        with:
          name: wasm-js-browser-files
          path: ./downloaded

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/') # Only run on tag push
        with:
          body: |
            Please check the [CHANGELOG.md](https://github.com/panpf/zoomimage/blob/main/CHANGELOG.md) file for updated log.

            Mobile app, desktop app and web deployable packages, see the Assets attachment.

            Web example：https://panpf.github.io/zoomimage/app.
          files: ./downloaded/*
          make_latest: true