name: Test

on: workflow_dispatch

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run desktop test
        run: ./gradlew desktopTest